#pragma once

class Event {
public:
	enum FD_TYPE {
		FD_UNKNOWN,
		FD_MOUSE_EVENT,
		FD_MOUSE_ACTION_MOVE,
		FD_MOUSE_ACTION_BUTTON_PRESSED,
		FD_MOUSE_ACTION_BUTTON_RELEASED,

		FD_WINDOW_EVENT,
		FD_WINDOW_ACTION_RESIZE,
		FD_WINDOW_ACTION_MOVE,
		FD_WINDOW_STATE_MINIMIZED,
		FD_WINDOW_STATE_MAXIMIZED,
		FD_WINDOW_STATE_FOCUS_GAINED,
		FD_WINDOW_STATE_FOCUS_LOST,
		
		FD_KEYBOARD_EVENT,
		FD_KEYBOARD_ACTION_KEY_PRESSED,
		FD_KEYBOARD_ACTION_KEY_RELEASED
	};

protected:
	FD_TYPE type;

public:
	Event(FD_TYPE type) { this->type = type; }

	inline FD_TYPE GetEventType() const { return type; }
};
