#pragma once
#include <util/string.h>

enum FD_TEXTURE2D_FORMAT {
	FD_TEXTURE2D_FORMAT_UNKNOWN,
	FD_TEXTURE2D_FORMAT_UINT_8_8_8_8,
	FD_TEXTURE2D_FORMAT_FLOAT_32_32_32_32
};

enum FD_INDEXBUFFER_FORMAT {
	FD_INDEXBUFFER_FORMAT_UNKNOWN,
	FD_INDEXBUFFER_FORMAT_UINT32,
	FD_INDEXBUFFER_FORMAT_INT32,
	FD_INDEXBUFFER_FORMAT_UINT16,
	FD_INDEXBUFFER_FORMAT_INT16,
};

inline static String get_format_string(FD_TEXTURE2D_FORMAT format) {
	switch (format) {
		case FD_TEXTURE2D_FORMAT_UNKNOWN: return ("FD_TEXTURE2D_FORMAT_UBKNOWN");
		case FD_TEXTURE2D_FORMAT_UINT_8_8_8_8: return ("FD_TEXTURE2D_FORMAT_UINT_8_8_8_8");
		case FD_TEXTURE2D_FORMAT_FLOAT_32_32_32_32: return ("FD_TEXTURE2D_FORMAT_FLOAT_32_32_32_32");
	}
	return ("ERROR");
}

inline static String get_format_string(FD_INDEXBUFFER_FORMAT format) {
	switch (format) {
		case FD_INDEXBUFFER_FORMAT_UNKNOWN: return ("FD_INDEXBUFFER_FORMAT_UNKNOWN");
		case FD_INDEXBUFFER_FORMAT_UINT32: return ("FD_INDEXBUFFER_FORMAT_UINT32");
		case FD_INDEXBUFFER_FORMAT_INT32: return ("FD_INDEXBUFFER_FORMAT_INT32");
		case FD_INDEXBUFFER_FORMAT_UINT16: return ("FD_INDEXBUFFER_FORMAT_UINT16");
		case FD_INDEXBUFFER_FORMAT_INT16: return ("FD_INDEXBUFFER_FORMAT_INT16");
	}
	return ("ERROR");
}

